feat/114 admin img upload
baza-trainee/450-kherson-humanitarian-landing-page pull request #121
Opened 2023-10-18 20:59 UTC by Bittersweet-girl

- Remove trash icon
- Change component to forward ref
- add API props

2023-10-21 07:45 UTC, AmelianceSkyMusic commented on src/components/ImgUpload/ImgUpload.tsx
> +				process.env.NODE_ENV === 'development' ? setImage(`${apiUrl}${file}`) : setImage(file);
Отака штука не вітається, в airbnb було за це атата. Краще мабуть так:
```jsx
const imgUrl = process.env.NODE_ENV === 'development' ? `${BASE_URL}${file}` : file;
setImage(imgUrl);
```

2023-10-21 07:49 UTC, AmelianceSkyMusic commented on src/components/ImgUpload/ImgUpload.tsx
> +	const apiUrl = process.env.BASE_URL;
У нас є константи, чому ви юзаєте все тут.

Чому тут ви тут  process.env.BASE_URL присвоюєте в змінну, а process.env.NODE_ENV ні?

Якщо ви присвоюєте константи може їх краще винести за компонент?

2023-10-21 07:54 UTC, AmelianceSkyMusic commented on src/components/ImgUpload/ImgUpload.tsx
> +				}
Дичина, не роби вкладені тернарники
І може краще це винести

2023-10-21 07:59 UTC, AmelianceSkyMusic commented on src/components/ImgUpload/ImgUpload.module.scss
> +	}
Краще замість цього заюзати міксин useOnHover, щоб не було потім нюансів

2023-10-21 08:00 UTC, AmelianceSkyMusic commented on src/components/ImgUploadWrapper/ImgUploadWrapper.tsx
> +	gradientValue,
Додай простору

2023-10-21 08:06 UTC, AmelianceSkyMusic commented on next.config.js
> +	},
Підтягни develop, ця штука вже є в коді

2023-10-21 09:39 UTC, Bittersweet-girl commented on next.config.js
> +	},
в девелопі було це теж, але видалила

2023-10-21 09:40 UTC, Bittersweet-girl commented on src/components/ImgUpload/ImgUpload.tsx
> +				process.env.NODE_ENV === 'development' ? setImage(`${apiUrl}${file}`) : setImage(file);
виправила

2023-10-21 09:40 UTC, Bittersweet-girl commented on src/components/ImgUpload/ImgUpload.tsx
> +				}
трохи винесла

2023-10-21 09:40 UTC, Bittersweet-girl commented on src/components/ImgUploadWrapper/ImgUploadWrapper.tsx
> +	gradientValue,
додала

2023-10-21 11:09 UTC, Bittersweet-girl commented on src/components/ImgUpload/ImgUpload.tsx
> +	const apiUrl = process.env.BASE_URL;
додалась константа

2023-10-21 11:10 UTC, Bittersweet-girl commented on src/components/ImgUpload/ImgUpload.module.scss
> +	}
додала міксин

2023-10-21 11:23 UTC, AmelianceSkyMusic requested changes

2023-10-21 11:23 UTC, AmelianceSkyMusic commented on src/components/ImgUploadWrapper/ImgUploadWrapper.tsx
> +>>>>>>> Stashed changes
Щось тут мердж не вдався)

2023-10-21 11:23 UTC, AmelianceSkyMusic commented on src/components/ImgUploadWrapper/ImgUploadWrapper.module.scss
> +.ImgUpload {
А цей файлик [ImgUploadWrapper.module.scss](https://github.com/baza-trainee/450-kherson-humanitarian-landing-page/pull/121/files#diff-54ef3857d2408518d7ceb28179c9d87af3163f1b88407917d655e2a3cc9e960c) точно має бути для врапера?

2023-10-21 11:23 UTC, AmelianceSkyMusic commented on next.config.js
А хіба в тебе не мало з'явитись
env: {
		BASE_URL: process.env.BASE_URL,
	},
	Якщо ти підтягувала з develop?

2023-10-21 12:17 UTC, Bittersweet-girl commented on next.config.js
так воно має бути, чи ні?

2023-10-22 10:13 UTC, AmelianceSkyMusic commented on next.config.js
Має

2023-10-22 12:38 UTC, Bittersweet-girl commented on next.config.js
ок, виправила

2023-10-24 08:53 UTC, AndreyLuchko approved these changes

2023-10-24 08:56 UTC, AmelianceSkyMusic approved these changes

2023-10-24 08:57 UTC, AmelianceSkyMusic approved these changes

2023-10-24 08:57 UTC, AmelianceSkyMusic commented on src/components/ImgUpload/ImgUpload.tsx
> +ImgUpload.displayName = 'ImgUpload';
Якщо хочеш можеш тут додати також відступ

2023-10-24 10:27 UTC, merged