Refactor/26-arrow-up-button
baza-trainee/450-kherson-humanitarian-landing-page pull request #15
Opened 2023-07-07 13:31 UTC by Anastasia-front

change color variables

2023-07-07 19:33 UTC, AmelianceSkyMusic requested changes

2023-07-14 18:53 UTC, Anastasia-front commented on src/components/Buttons/ArrowUpButton.tsx
> +			<span className={clsx(s.label)}>{children}</span>
з цим вже розібралася)

2023-07-24 16:54 UTC, AmelianceSkyMusic approved these changes

2023-07-24 16:59 UTC, Anastasia-front commented on src/components/Buttons/ArrowUpButton.tsx
> +			<span className={clsx(s.label)}>{children}</span>
іконка є, ось
<img width="517" alt="image" src="https://github.com/baza-trainee/450-kherson-humanitarian-landing-page/assets/115567693/d0e8e034-3e24-445c-afb5-fb407af5c98f">

2023-07-24 16:59 UTC, Anastasia-front commented on src/components/Buttons/ArrowUpButton.tsx
домовилися, що логіка тут і буде в компоненті

2023-07-24 17:11 UTC, AmelianceSkyMusic commented on src/components/Buttons/ArrowUpButton.tsx
> +			<span className={clsx(s.label)}>{children}</span>
це старе, коли дивишся коменти, резовли, щоб потім не плутатись

2023-07-24 17:12 UTC, AmelianceSkyMusic commented on src/components/Buttons/ArrowUpButton.tsx
з ким?) Логіка мається на увазі не оці маніпуляції з дом, але то вже «на майбутнє»

2023-07-24 17:19 UTC, Anastasia-front commented on src/components/Buttons/ArrowUpButton.tsx
та ніби всі разом це обговорювали - може щось не так зрозуміла

2023-07-24 18:04 UTC, AndreyLuchko approved these changes

2023-07-25 10:02 UTC, merged