refactor/78-modal
baza-trainee/450-kherson-humanitarian-landing-page pull request #25
Opened 2023-07-18 19:34 UTC by AndreyLuchko

- Add component Modal with styles
- Add Portal component
- Add hook for lock and unlock scroll

2023-07-20 16:28 UTC, Anastasia-front commented on src/hooks/useScrollBarWidth.ts
> +}
у мене цей самий хук, який блочить скролл при відкритому бургер меню - назвала як в бібліотеці Раджаба
може зміниш назву файла як у нього - useScrollLock?
щоб вже було в нас однаково

2023-07-20 16:37 UTC, Anastasia-front commented on src/components/Modal/Modal.module.scss
> +	min-height: 14px;
ця висота всюди одна, можна просто зафіксувати як height

2023-07-20 16:42 UTC, AmelianceSkyMusic requested changes

2023-07-20 16:42 UTC, AmelianceSkyMusic commented on src/components/Modal/Modal.tsx
> +	}, [onClose]);
Управляти домом напряму це не по реактівськи
Повісь кудись onKeyUp

2023-07-20 16:42 UTC, AmelianceSkyMusic commented on src/components/Modal/Modal.tsx
> +			<div className={s.modalContainer} onClick={() => onClose()}>
а чому просто не передаєш колбек onClose?

2023-07-20 16:42 UTC, AmelianceSkyMusic commented on src/components/Modal/Modal.tsx
> +				<div className={s.modal} onClick={(e) => e.stopPropagation()}>
Для чого тут це?

2023-07-20 16:42 UTC, AmelianceSkyMusic commented on src/components/Modal/Modal.tsx
> +							onClick={() => onClose()}
а чому просто не передаєш колбек onClose?

2023-07-20 16:53 UTC, Anastasia-front commented on src/components/Modal/Modal.tsx
> +	}, [onClose]);
useEffect(() => {
		const handleKeyDown = (e: KeyboardEvent) => {
			if (e.code === 'Escape') {
				onMenuOpen(false);
			}
		};
		window.addEventListener('keydown', handleKeyDown);
		return () => {
			window.removeEventListener('keydown', handleKeyDown);
		};
	}, [onMenuOpen]);
	
	в мене виходить та сама історія
	виходить треба замінити 'keydown' на keyup'?

2023-07-21 06:55 UTC, AndreyLuchko commented on src/components/Modal/Modal.tsx
> +	}, [onClose]);
> Управляти домом напряму це не по реактівськи Повісь кудись onKeyUp
А як? Хук користуватьский? 
замінити 'keydown' на keyup'?

2023-07-24 17:09 UTC, AndreyLuchko commented on src/components/Modal/Modal.tsx
> +				<div className={s.modal} onClick={(e) => e.stopPropagation()}>
щоб при кліку на мод вікно воно не закривалося

2023-07-24 19:03 UTC, Anastasia-front approved these changes

2023-07-24 19:04 UTC, Anastasia-front approved these changes

2023-07-24 19:05 UTC, Anastasia-front approved these changes

2023-07-25 11:48 UTC, Anastasia-front approved these changes

2023-07-25 11:51 UTC, AndreyLuchko commented on src/hooks/useKeyPress.ts
> +			if ((event as unknown as KeyboardEvent).key === key) {
Resolve

2023-07-25 13:37 UTC, merged