feat/21-about-us
baza-trainee/450-kherson-humanitarian-landing-page pull request #28
Opened 2023-07-20 19:05 UTC by AndreyLuchko

add block AboutUs with styles and adaptive

2023-07-21 22:41 UTC, AmelianceSkyMusic requested changes

2023-07-21 22:41 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.module.scss
> +	& .item:first-child p {
Не простіше клас задати? сам потім згадаєш що в коді робить?

2023-07-21 22:41 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.tsx
> +											<Image src={obj.src} alt={`${obj.id} icon`} width={48} height={48} />
дивно, що іконки ти підгружаєш через шлях, а зображення через імпорт, чому все не зробити через шлях? наприклад
![image](https://github.com/baza-trainee/450-kherson-humanitarian-landing-page/assets/38717657/0a200b7f-ce48-49fc-96f6-e96c22318306)

2023-07-21 22:41 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.module.scss
> +	&:nth-child(2) .text {
Можливо можна якось простіше?

2023-07-21 22:41 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.module.scss
> +	& h3 {
Навіщо тут амперсанд (і не тільки тут)?
Та і звідки знати по коду, що в тебе в компоненті Text приходить?

2023-07-21 22:41 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUsContent.ts
> +		text2: 'За рік плідної праці орендуємо вже 3 склади для гуманітарної допомоги. Завдяки нашим партнерам ми продовжуємо закривати потреби цивільних та долучатись до допомоги медичним закладам міста т
Це просто думка, робити нічого не потрібно, але я може б попробував зробити масивом)

2023-07-21 22:41 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUsContent.ts
> +export const ABOUT_US_CONTENT = {
Файл названий як компонент AboutUsContent.ts, всередині змінна названа як константа ABOUT_US_CONTENT, а в кінцевому рахунку це звичайна змінна з папки data/aboutUsContent.ts=)

2023-07-21 22:41 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.module.scss
> +}
не дуже зрозуміло нащо це тут, це кастомні величини саме для цього блоку?

2023-07-23 09:02 UTC, AndreyLuchko commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.tsx
> +											<Image src={obj.src} alt={`${obj.id} icon`} width={48} height={48} />
тому що іконки в public та підключаються із константи, а зображення у assets (довший шлях, та якось простіше в src зображення написати просто назву, ніж цей довжелезний шлях)

2023-07-23 09:07 UTC, AndreyLuchko commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.module.scss
> +	& .item:first-child p {
1. цього костиля могло б не бути, якщо б не треба було переносити строки по дізайну. 
2. цей тег 'p' підключаєтеся через map()

2023-07-23 09:26 UTC, AndreyLuchko commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUsContent.ts
> +		text2: 'За рік плідної праці орендуємо вже 3 склади для гуманітарної допомоги. Завдяки нашим партнерам ми продовжуємо закривати потреби цивільних та долучатись до допомоги медичним закладам міста т
спочатку так і робив, але там мінялись відступи, потім додавали переноси, я зробив окремо.
Ще подумав, може текст буде мінятися через адмінку, та так може буде зручніше?

2023-07-23 10:14 UTC, AndreyLuchko commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.module.scss
> +}
видалив, але додав відступ у компонент Section як для мобільних

2023-07-23 10:18 UTC, AndreyLuchko commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUsContent.ts
> +export const ABOUT_US_CONTENT = {
зробити так AboutUs/constants/ABOUT_US_CONTENT.ts ?
чи так  AboutUs/ABOUT_US_CONTENT.ts ?

2023-07-24 14:52 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.module.scss
> +	& .item:first-child p {
Цей амперсанд тут нічого не робить

2023-07-24 14:52 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.tsx
> +import { ABOUT_US_CONTENT } from './constants/ABOUT_US_CONTENT';
Це ж в тебе не константи, а звичайні дані. Якщо воно потім не прибереться і не видалиться коли з'явиться бек, то може одразу змінити?

2023-07-24 17:08 UTC, AmelianceSkyMusic approved these changes

2023-07-24 17:23 UTC, merged