feat: create styles for ourPartners block
baza-trainee/450-kherson-humanitarian-landing-page pull request #8
Opened 2023-07-01 15:31 UTC by Anastasia-front

all logic of work with array of partner's logos I wrote in comments

2023-07-02 18:23 UTC, AndreyLuchko commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.tsx
Загалом: запит на мердж з гілкою мейн
Чому у блоці AboutUs, а не OurPartner?
Чому саме 130 довжина карток?

2023-07-02 18:23 UTC, AndreyLuchko commented on src/components/Container/Container.module.scss
Якщо вже є контейнера довжина, то краще мабуть другий медіа запит робити для мобілок...?

2023-07-03 11:11 UTC, Anastasia-front commented on src/pageComponents/HomePage/blocks/AboutUs/AboutUs.tsx
все змінила

2023-07-03 11:11 UTC, Anastasia-front commented on src/components/Container/Container.module.scss
це не зрозуміла ...

2023-07-24 17:05 UTC, AmelianceSkyMusic requested changes

2023-07-24 17:05 UTC, AmelianceSkyMusic commented on src/components/Container/Container.module.scss
>  }
Поверни як було, щось ти дивне робиш=)

2023-07-24 17:05 UTC, AmelianceSkyMusic commented on src/pageComponents/HomePage/blocks/OurPartners/partners.ts
> +import partner2 from '../../../../assets/images/partners/society-of-ukrainians-in-Finland.png';
О, нініні, ми таке не робимо, у нас же є аліаси=)

2023-07-24 17:07 UTC, Anastasia-front commented on src/pageComponents/HomePage/blocks/OurPartners/partners.ts
> +import partner2 from '../../../../assets/images/partners/society-of-ukrainians-in-Finland.png';
перероблю зараз

2023-07-24 17:16 UTC, Anastasia-front commented on src/pageComponents/HomePage/blocks/OurPartners/partners.ts
> +import partner2 from '../../../../assets/images/partners/society-of-ukrainians-in-Finland.png';
зробила

2023-07-24 17:22 UTC, Anastasia-front commented on src/components/Container/Container.module.scss
>  }
це зі старого коміту, зараз вже по-іншому

2023-07-25 18:15 UTC, AmelianceSkyMusic approved these changes
Апрув наче=)

2023-07-25 18:24 UTC, merged