refactor/44-text-button
baza-trainee/450-kherson-humanitarian-landing-page pull request #9
Opened 2023-07-03 11:39 UTC by Anastasia-front

create text button component

2023-07-07 19:41 UTC, AmelianceSkyMusic requested changes

2023-07-07 19:41 UTC, AmelianceSkyMusic commented on src/components/Buttons/TextButton.module.scss
> +}
Переглянь змінні кольорів

2023-07-07 19:41 UTC, AmelianceSkyMusic commented on src/components/Buttons/TextButton.tsx
> +				<span className={clsx(s.label)}>{children}</span>
тут clsx не потрібен

2023-07-07 19:41 UTC, AmelianceSkyMusic commented on src/components/Buttons/TextButton.module.scss
> +}
вклади це все як disabled у відповідний клас, щоб воно аплаїлось при комбінації `.secondary.disabled`
`.primary.disabled`

2023-07-07 19:41 UTC, AmelianceSkyMusic commented on src/components/Buttons/TextButton.tsx
> +			disabled && type === 'secondary' && s.disabledSecondary,
прибери перевірку на тип, лиши просто на disabled && s.disabled і зроби через комбінацію класів `.secondary.disabled` `.primary.disabled`

2023-07-08 11:19 UTC, Anastasia-front commented on src/components/Buttons/TextButton.tsx
> +			disabled && type === 'secondary' && s.disabledSecondary,
done

2023-07-08 11:20 UTC, Anastasia-front commented on src/components/Buttons/TextButton.tsx
> +				<span className={clsx(s.label)}>{children}</span>
видалила

2023-07-08 11:20 UTC, Anastasia-front commented on src/components/Buttons/TextButton.module.scss
> +}
це провтикала...

2023-07-08 11:24 UTC, Anastasia-front commented on src/components/Buttons/TextButton.module.scss
> +}
з вкладенням не підключаються стилі, тільки якщо отак прописати .secondary.disabled

2023-07-08 11:47 UTC, AndreyLuchko commented on src/components/Buttons/Button.tsx
> +				<span className={s.label}>{children}</span>
Можливо замість span, вже можна компонент Text використовувати...?

2023-07-08 11:55 UTC, AndreyLuchko requested changes

2023-07-08 11:55 UTC, AndreyLuchko commented on src/components/Buttons/Button.tsx
> +				<span className={s.label}>{children}</span>
Можливо замість span, вже можна компонент Text використовувати...?

2023-07-08 12:52 UTC, Anastasia-front commented on src/components/Buttons/Button.tsx
> +				<span className={s.label}>{children}</span>
виправила

2023-07-08 13:36 UTC, AmelianceSkyMusic approved these changes

2023-07-08 13:46 UTC, AndreyLuchko approved these changes

2023-07-08 13:47 UTC, merged